### ISSUE TITLE
Keeping anchors with ID hrefs in the same tab

### ISSUE THREAD

**Issue by jozanza** [egoist/mmark#7]
While the `linksInNewTab` option is awesome, I'd like it to only affect non-id hrefs. Opening a new tab with the same page but in a different scroll position doesn't make for a great experience imho. I created a PR to fix this by checking the leading character of a link's href attribute. Please let me know if this is something you are into @egoist or if there are changes you'd like me to make 👍

**Comment by egoist** [comment]
maybe we can allow `linksInNewTab` to be a function which could be used to test against the href value? since there seems to be other cases where you don't want to make it open in new tab.

**Comment by jozanza** [comment]
That's cool too. My main issue is I've used [docup](https://github.com/egojump/docup) to generate some [API documentation](https://livepeer.github.io/livepeerjs/sdk/#api), and navigating it is out-of-hand.

**Comment by egoist** [comment]
@jozanza hah yep, I noticed that issue too but haven't got time to look into it!

**Comment by jozanza** [comment]
If you're down with the function approach, I can update my PR in this repo, and create a PR in docup to allow folks to pass in that function via the `options` object when constructing a `new Docup()`

**Comment by egoist** [comment]
sure 👍🏻please

**Comment by egoist** [comment]
also we can set `linksInNewTab` in docup to a function that could handle some common cases, maybe anything not starting with `https?://`

**Comment by jozanza** [comment]
You got it 🍻

**Comment by jozanza** [comment]
@egoist I made the change and bumped the version to `0.6.1`, so I can fork docup and create a PR with an updated version of marked3. Let me know if you want any changes 👍

EDIT: Also here's the [docup PR](https://github.com/egojump/docup/pull/8). We'll probably want to update the `marked3` version in `package.json` after this PR is merged and a new version is published.
